---

- name: download jbeap
  get_url: url=http://<>/JBEAP-6/{{ jboss_verions.release }}/jboss-eap-{{ jboss_verions.release }}-full-build.zip dest=/opt/jboss-eap-{{ jboss_verions.release }}-full-build.zip
  tags: eap-install

- name: Extract archive
  unarchive: src=/opt/jboss-eap-{{ jboss_verions.release }}-full-build.zip dest=/opt/ creates=/usr/share/jboss-as
  tags: eap-install
  
- name: Rename install directory
  command: chdir=/usr/share /bin/mv /opt/jboss-eap-{{ jboss_verions.version }} jboss-as creates=/usr/share/jboss-as
     
- name: Create directory /etc/jboss-as
  file: path=/etc/jboss-as state=directory

- name: Config jboss-as.conf
  action: template src=../templates/jboss-as.conf.j2 dest=/etc/jboss-as/jboss-as.conf
           
- name: Add group "jboss"
  group: name={{ jboss_user }}
               
- name: Add user "jboss"
  user: name={{ jboss_user }} group={{ jboss_user }} home=/usr/share/jboss-as
                   
- name: Change ownership
  file: path={{ item }} owner={{ jboss_user }} group={{ jboss_user }} state=directory recurse=yes
  with_items:
    - /usr/share/jboss-as/
    - /var/run/jboss-as/

- name: Config the init script
  copy: src=/usr/share/jboss-as/bin/init.d/jboss-as-standalone.sh dest=/etc/init.d/jbossas mode=0755
                           
- name: Restart jbossas
  service: name=jbossas enabled=yes state=restarted
  
