---

## Install the offical rvm roles first  [doc] https://github.com/rvm/rvm1-ansible
# `Please remember to update ansible first if needed`
# sudo ansible-galaxy install rvm_io.ruby 

- name: Configure servers with ruby support
  hosts: localhost

  roles:
    - { role: rvm_io.ruby, 
        tags: ruby, 
        become: yes,
        rvm1_rubies: ['ruby-2.2.2','ruby-2.2.5'],
        rvm1_install_flags: '--auto-dotfiles --user-install',
        rvm1_install_path: '/home/wguo/.rvm',
        rvm1_user: 'wguo',
      }

## Config env 
# vim ~/.bash_profile
# append "$HOME/.rvm/bin" to PATH
# source ~/.base_profile
# [wguo@wguo ansible-sample]$ rvm list
#
# rvm rubies
#
#    ruby-2.2.2 [ x86_64 ]
#    =* ruby-2.2.5 [ x86_64 ]
#
#    # => - current
#    # =* - current && default
#    #  * - default

